"""initial knowledge desk schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-11 15:36:46.065209
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

import knowledge_desk.domain.models


revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('avatar_url', sa.String(length=510), nullable=True),
    sa.Column('created_at', knowledge_desk.domain.models.UTCDateTime(), nullable=False),
    sa.Column('updated_at', knowledge_desk.domain.models.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('knowledge_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.Enum('web', 'pdf', 'markdown', 'snippet', 'docx', 'pptx', 'html', 'txt', name='sourcetype', native_enum=False, length=32), nullable=False),
    sa.Column('title', sa.String(length=510), nullable=False),
    sa.Column('source_uri', sa.String(length=2048), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=False),
    sa.Column('cleaned_content', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('inbox', 'processing', 'ready', 'failed', 'archived', name='knowledgestatus', native_enum=False, length=32), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('archived_at', knowledge_desk.domain.models.UTCDateTime(), nullable=True),
    sa.Column('created_at', knowledge_desk.domain.models.UTCDateTime(), nullable=False),
    sa.Column('updated_at', knowledge_desk.domain.models.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_items', schema=None) as batch_op:
        batch_op.create_index('ix_knowledge_items_user_content_hash', ['user_id', 'content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_items_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_knowledge_items_user_status_updated', ['user_id', 'status', 'updated_at'], unique=False)

    op.create_table('model_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider_type', sa.Enum('openai', 'deepseek', 'local_compatible', 'custom', name='providertype', native_enum=False, length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('base_url', sa.String(length=510), nullable=False),
    sa.Column('default_model', sa.String(length=160), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('api_key_masked', sa.String(length=64), nullable=True),
    sa.Column('last_check_status', sa.Enum('ok', 'error', name='modelcheckstatus', native_enum=False, length=32), nullable=True),
    sa.Column('last_check_message', sa.String(length=255), nullable=True),
    sa.Column('last_checked_at', knowledge_desk.domain.models.UTCDateTime(), nullable=True),
    sa.Column('created_at', knowledge_desk.domain.models.UTCDateTime(), nullable=False),
    sa.Column('updated_at', knowledge_desk.domain.models.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_model_sources_user_name')
    )
    with op.batch_alter_table('model_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_sources_user_id'), ['user_id'], unique=False)

    op.create_table('tags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('created_at', knowledge_desk.domain.models.UTCDateTime(), nullable=False),
    sa.Column('updated_at', knowledge_desk.domain.models.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_tags_user_name')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_user_id'), ['user_id'], unique=False)

    op.create_table('user_preferences',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('organize_mode', sa.Enum('manual', 'auto', name='organizemode', native_enum=False, length=32), nullable=False),
    sa.Column('privacy_mode', sa.Enum('local_first', 'cloud_first', name='privacymode', native_enum=False, length=32), nullable=False),
    sa.Column('default_model_source_id', sa.String(length=36), nullable=True),
    sa.Column('summary_model_source_id', sa.String(length=36), nullable=True),
    sa.Column('tagging_model_source_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', knowledge_desk.domain.models.UTCDateTime(), nullable=False),
    sa.Column('updated_at', knowledge_desk.domain.models.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('knowledge_item_id', sa.String(length=36), nullable=False),
    sa.Column('job_type', sa.Enum('import', 'organize', 'reprocess', name='ingestionjobtype', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'succeeded', 'failed', name='ingestionjobstatus', native_enum=False, length=32), nullable=False),
    sa.Column('error_message', sa.String(length=255), nullable=True),
    sa.Column('note', sa.String(length=120), nullable=True),
    sa.Column('started_at', knowledge_desk.domain.models.UTCDateTime(), nullable=True),
    sa.Column('finished_at', knowledge_desk.domain.models.UTCDateTime(), nullable=True),
    sa.Column('created_at', knowledge_desk.domain.models.UTCDateTime(), nullable=False),
    sa.Column('updated_at', knowledge_desk.domain.models.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_item_id'], ['knowledge_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingestion_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingestion_jobs_knowledge_item_id'), ['knowledge_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingestion_jobs_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_ingestion_jobs_user_item_created', ['user_id', 'knowledge_item_id', 'created_at'], unique=False)

    op.create_table('knowledge_item_tags',
    sa.Column('knowledge_item_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_item_id'], ['knowledge_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('knowledge_item_id', 'tag_id')
    )
    op.create_table('review_states',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('knowledge_item_id', sa.String(length=36), nullable=False),
    sa.Column('due_at', knowledge_desk.domain.models.UTCDateTime(), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('ease_factor', sa.Float(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('last_rating', sa.Enum('again', 'hard', 'good', 'easy', name='reviewrating', native_enum=False, length=32), nullable=True),
    sa.Column('last_reviewed_at', knowledge_desk.domain.models.UTCDateTime(), nullable=True),
    sa.Column('created_at', knowledge_desk.domain.models.UTCDateTime(), nullable=False),
    sa.Column('updated_at', knowledge_desk.domain.models.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_item_id'], ['knowledge_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'knowledge_item_id', name='uq_review_states_user_item')
    )
    with op.batch_alter_table('review_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_states_knowledge_item_id'), ['knowledge_item_id'], unique=False)
        batch_op.create_index('ix_review_states_user_due', ['user_id', 'due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_states_user_id'), ['user_id'], unique=False)

    op.create_table('source_assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('knowledge_item_id', sa.String(length=36), nullable=False),
    sa.Column('original_filename', sa.String(length=510), nullable=False),
    sa.Column('stored_relative_path', sa.String(length=510), nullable=False),
    sa.Column('mime_type', sa.String(length=160), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('origin', sa.Enum('picker', 'watched_folder', name='sourceassetorigin', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', knowledge_desk.domain.models.UTCDateTime(), nullable=False),
    sa.Column('updated_at', knowledge_desk.domain.models.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_item_id'], ['knowledge_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('knowledge_item_id')
    )
    with op.batch_alter_table('source_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_assets_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_assets_user_id'))

    op.drop_table('source_assets')
    with op.batch_alter_table('review_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_states_user_id'))
        batch_op.drop_index('ix_review_states_user_due')
        batch_op.drop_index(batch_op.f('ix_review_states_knowledge_item_id'))

    op.drop_table('review_states')
    op.drop_table('knowledge_item_tags')
    with op.batch_alter_table('ingestion_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_ingestion_jobs_user_item_created')
        batch_op.drop_index(batch_op.f('ix_ingestion_jobs_user_id'))
        batch_op.drop_index(batch_op.f('ix_ingestion_jobs_knowledge_item_id'))

    op.drop_table('ingestion_jobs')
    op.drop_table('user_preferences')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_user_id'))

    op.drop_table('tags')
    with op.batch_alter_table('model_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_sources_user_id'))

    op.drop_table('model_sources')
    with op.batch_alter_table('knowledge_items', schema=None) as batch_op:
        batch_op.drop_index('ix_knowledge_items_user_status_updated')
        batch_op.drop_index(batch_op.f('ix_knowledge_items_user_id'))
        batch_op.drop_index('ix_knowledge_items_user_content_hash')

    op.drop_table('knowledge_items')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
