app:
  kafka:
    enabled: true

spring:
  kafka:
    consumer:
      auto-startup: true
  ai:
    vectorstore:
      milvus:
        client:
          host: ${MILVUS_HOST:localhost}
          port: ${MILVUS_PORT:19530}

# generic properties just in case
milvus:
  host: ${MILVUS_HOST:localhost}
  port: ${MILVUS_PORT:19530}

